services:
    postgres:
        image: postgres:15-alpine
        container_name: synapse_db
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: synapse_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/init-scripts:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - synapse_network

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: synapse_pgadmin
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@synapse.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - synapse_network

volumes:
    postgres_data:
    pgadmin_data:


networks:
    synapse_network:
        driver: bridge
